### ISSUE TITLE
Watch mode

### ISSUE THREAD

**Issue by a-s-o** [fuse-box/fuse-test-runner#11]
Hi,

Are there any plans to add a watch mode to the test runner? Currently test runner terminates after all tests are done.

I am doing this but the watch() does nothing. The runner still exists after first run:

```
  fuse
    .bundle('feature')
    .watch()
    .test('[**/**.test.ts]')
```

**Comment by a-s-o** [comment]
For other that are interested, I am currently using the following workaround:
```
  "scripts": {
    "test": "chokidar 'src/**/*.ts' -c 'node fuse test' --initial",
  },
```

Chokidar can be installed with `npm install chokidar-cli`

**Comment by nchanged** [comment]
That's a nice idea, could you submit an issue on fusebox repository, we will implement it for sure

**Comment by a-s-o** [comment]
Moved to fuse-box/fuse-box/issues/636
