### ISSUE TITLE
Ability to set timeout

### ISSUE THREAD

**Issue by dakom** [fuse-box/fuse-test-runner#12]
When I have a long running test, I hit "Timeout error" after 2 seconds.

I suspect it is due to this: https://github.com/fuse-box/fuse-test-runner/blob/a6059da27e752f4c223b2133597a5ea7b13fb2ff/src/Awaiting.ts#L18

But setting the FUSE_TEST_TIMEOUT as process.env variable (via cross-env) did not have an affect :(

Is it possible to configure this value? Preferably per-test _or_ globally like `jasmine.DEFAULT_TIMEOUT_INTERVAL`

**Comment by nchanged** [comment]
It's odd, but that variable does work personally for me, I have tests that take 5 sec to warmup

**Comment by dakom** [comment]
Hmmm okay I'll see if I can put together a standalone test, maybe I did something else wrong

**Comment by dakom** [comment]
here: https://github.com/dakom/temp-fuse-test - under `timer-test` branch (currently `master` too but that might change)

I used cross-env and EnvPlugin to confirm that FUSE_TEST_TIMEOUT is changed both at packaging level and from within the test itself.

Expected result: FUSE_TEST_TIMEOUT value of 30000 should allow the test to complete
What happens instead: at around 2 seconds a timeout error occurs

**Comment by nchanged** [comment]
Oh, have you tried settings it via terminal?
`FUSE_TEST_TIMEOUT=30000 node fuse`

**Comment by dakom** [comment]
Just tried, still fails

**Comment by dakom** [comment]
@nchanged - were you able to duplicate the problem from the [test repo](https://github.com/dakom/temp-fuse-test)?

**Comment by nchanged** [comment]
Sorry man, not yet, could u create an issue in fuse-box? So I won't forget

**Comment by dakom** [comment]
Tracked at https://github.com/fuse-box/fuse-box/issues/772
