### ISSUE TITLE
Using globals with test

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-test-runner#3]
Hi, I'm trying to use my stubbing plugin with the new bundler. It works well, when I build a running app, but it does not work when bundling tests.

This does not work:

```
fuse.bundle("app")
    .plugin([StubPlugin])
    .globals({ proxyrequire: '*' })
    .test("[**/**.test.tsx]");
```

Error:

```
(node:6617) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: proxyRequire is not defined
```

This works

```
luisFuse.bundle("client")
    .watch() // watch only client related code
    .hmr()
    .sourceMaps(true)
    .plugin([StubPlugin])
    .globals({ proxyrequire: '*' })
    .instructions(" !> [client/luis.ts]");
```

**Comment by nchanged** [comment]
Hm. it depends on what you StupPlugin does, besides...
I believe, your plugin should be set like this:
```
 .plugin(StubPlugin)
```
Have you tried doing `+ proxyRequire ` ?

**Comment by tomitrescak** [comment]
@nchanged StubPlugin changes all "require" to "proxyrequire" and allows to stub references in modules (beneficial in UI testing). I need to set then proxyrequire as a global variable. Before I was doing that manually but I figured out a way of how to do it via globals in fusebox and it works very well for my executable bundle. Yet it does not work in tests unfortunately ;(

**Comment by tomitrescak** [comment]
With tests I am not sure where is the entry point so I cannot specify proxyrequire manually. The best would be if the global would work. 

Looks like following line is not emitted in the test bundle:

```
FuseBox.expose([{"alias":"*","pkg":"proxyrequire"}]);
```

**Comment by tomitrescak** [comment]
Correction, when specified with basic configuraion, not via chainable API the line is there, yet it still does not work.

**Comment by tomitrescak** [comment]
I guess the problem is that in the executable bundle there is following chain:

```
FuseBox.expose([{"alias":"*","pkg":"proxyrequire"}]);

FuseBox.import("default/client/luis.js");
FuseBox.main("default/client/luis.js");
```

So first, the globals are exposed and then the bundle is executed.

While in tests:

```
});
FuseBox.expose([{"alias":"*","pkg":"proxyrequire"}]);
})
```

There is no single entry point ...

Therefore ... is there nay way I can define globals for my tests?

**Comment by nchanged** [comment]
I guess a solution is here: https://github.com/fuse-box/fuse-box/blob/master/src/BundleTestRunner.ts#L13

There is a different fuse instance for tests (no the original one, cuz it's a bundle in a bundle)
Maybe we should look in there

**Comment by tomitrescak** [comment]
Hmm, I checked and the globals DO exist in bundle (I guess it's still worth looking into why it does not work with chainable api) ... BUT ... they do not exist in the context of the test.

Yet this one line solved it all:

```
     start() {
        this.bundle.registerGlobals(); // this one

        const FuseBoxTestRunner = this.fuse.import("fuse-test-runner").FuseBoxTestRunner;
        const runner = new FuseBoxTestRunner(this.opts);
        runner.start();
    }
```

**Comment by tomitrescak** [comment]
You gotta love a system where a complex problem can be solved with one line of code ;)

**Comment by nchanged** [comment]
@tomitrescak nice =)
